export * from './moviesListCard/MoviesListCard';
export * from './moviesList/MoviesList';
export * from './header/Header';
export * from './movieInfo/MovieInfo';
export * from './genres/Genres';
export * from './genres/Genre';
export * from './movieInfo/movieI';
export * from './userInfo/UserInfo';
export * from './seacrhBox/SearchBox'